import fs from 'fs';
import path from 'path';

const translations = new Map([
  // ===== adapters leftovers =====
  ['// Constants (复用 sol-sdk/jito 配置)', '// Constants (reuses sol-sdk/jito config)'],
  ['// Singleton Management (与 RpcAdapter 一致的模式)', '// Singleton Management (same pattern as RpcAdapter)'],
  [`Jito getTipAccounts 错误`, `Jito getTipAccounts error`],
  ['// Cache每个价格', '// Cache each price'],

  // ===== const/index.ts =====
  ['// 用户配置存储key', '// User config storage key'],

  // ===== wallet-store.ts =====
  ['ForgeX CLI 钱包存储', 'ForgeX CLI Wallet Store'],
  ['本地加密存储钱包组数据，替代前端的 IndexedDB 持久化方案。', 'Locally encrypted wallet group storage, replacing the frontend IndexedDB persistence.'],
  ['使用 AES 加密私钥（静态加密），支持 KDF v3 格式导入/导出。', 'Uses AES encryption for private keys (encryption at rest), supports KDF v3 format import/export.'],
  ['加密方案：', 'Encryption scheme:'],
  ['每个 WalletInfo.privateKey 字段使用 CryptoJS AES 加密存储', 'Each WalletInfo.privateKey field is stored encrypted with CryptoJS AES'],
  ['master password 通过 FORGEX_PASSWORD 环境变量或 inquirer 交互输入', 'Master password via FORGEX_PASSWORD env var or inquirer interactive prompt'],
  ['WalletStoreData.encrypted 标记区分加密格式和旧明文格式', 'WalletStoreData.encrypted flag distinguishes encrypted format from legacy plaintext'],
  ['旧格式自动迁移到加密格式', 'Legacy format auto-migrates to encrypted format'],
  ['// 加密模式下存储 AES 密文，明文模式下存储 Base58 私钥', '// Stores AES ciphertext in encrypted mode, Base58 private key in plaintext mode'],
  ['/** 标记存储是否已加密。true 表示 privateKey 字段为 AES 密文 */', '/** Whether storage is encrypted. true means privateKey fields are AES ciphertext */'],
  ['/** 用于验证密码正确性的校验值（加密后的已知明文） */', '/** Checksum for password verification (encrypted known plaintext) */'],
  ['/** 用于密码校验的已知明文标记 */', '/** Known plaintext marker for password verification */'],
  ['// Master Password 管理', '// Master Password Management'],
  ['/** 运行时内存中的 master password（进程生命周期内有效） */', '/** Runtime in-memory master password (valid for process lifetime) */'],
  ['设置 master password（供 CLI 入口调用）', 'Set master password (called from CLI entry point)'],
  ['密码将保存在内存中，仅在当前进程生命周期内有效。', 'Password is saved in memory, only valid for current process lifetime.'],
  ['获取当前 master password', 'Get current master password'],
  ['优先级：内存中的密码 > 环境变量 FORGEX_PASSWORD', 'Priority: in-memory password > FORGEX_PASSWORD env var'],
  ['确保 master password 已设置。', 'Ensure master password is set.'],
  ['如果未设置，尝试从环境变量读取；如果仍未获取到，通过 inquirer 交互提示输入。', 'If not set, tries env var; if still not available, prompts via inquirer interactive input.'],
  ['此函数为异步函数，因为可能需要等待用户输入。', 'This function is async because it may need to wait for user input.'],
  ['// 动态导入 inquirer 以避免在不需要时加载', '// Dynamically import inquirer to avoid loading when not needed'],
  ["message: '请输入钱包加密密码 (master password):'", "message: 'Enter wallet encryption password (master password):'"],
  ["throw new Error('密码不能为空')", "throw new Error('Password cannot be empty')"],
  ['// 私钥加解密', '// Private Key Encryption/Decryption'],
  ['/** 使用 master password 加密一个私钥 */', '/** Encrypt a private key with master password */'],
  ['/** 使用 master password 解密一个私钥 */', '/** Decrypt a private key with master password */'],
  ["throw new Error('私钥解密失败：密码错误或数据已损坏')", "throw new Error('Private key decryption failed: wrong password or corrupted data')"],
  ['解密单个 WalletInfo 的私钥（供 SDK 和命令调用）', 'Decrypt a single WalletInfo private key (for SDK and command use)'],
  ['如果存储未加密（旧格式），直接返回原始 privateKey。', 'If storage is unencrypted (legacy format), returns original privateKey directly.'],
  ['如果已加密，使用 master password 解密后返回 Base58 明文私钥。', 'If encrypted, decrypts with master password and returns Base58 plaintext private key.'],
  ['// 如果没有设置密码，假定为未加密格式，直接返回', '// If no password set, assume unencrypted format, return directly'],
  ['// 尝试解密', '// Try to decrypt'],
  ['// 验证解密结果是否为有效的 Base58 私钥', '// Verify decrypted result is a valid Base58 private key'],
  ['// 如果解密失败，可能是未加密的明文私钥（向后兼容）', '// If decryption fails, may be unencrypted plaintext private key (backward compatible)'],
  ['私钥解密失败：密码错误或私钥数据已损坏', 'Private key decryption failed: wrong password or corrupted key data'],
  ['异步版本的解密函数，会自动确保密码已设置', 'Async version of decryption function, auto-ensures password is set'],
  ['/** 生成密码校验值 */', '/** Generate password checksum */'],
  ['/** 验证密码是否正确 */', '/** Verify if password is correct */'],
  ['// 存储操作', '// Storage Operations'],
  ['/** 加载钱包存储数据（原始格式，不解密私钥） */', '/** Load wallet store data (raw format, does not decrypt private keys) */'],
  ['// 文件损坏：备份损坏文件并警告用户', '// File corrupted: backup corrupted file and warn user'],
  ['警告: 钱包存储文件已损坏，已备份至', 'Warning: wallet store file is corrupted, backed up to'],
  ['。将使用空数据继续运行。', '. Will continue with empty data.'],
  ['警告: 钱包存储文件已损坏且无法创建备份。将使用空数据继续运行。', 'Warning: wallet store file is corrupted and backup failed. Will continue with empty data.'],
  ['/** 保存钱包存储数据 */', '/** Save wallet store data */'],
  ['// 加密迁移', '// Encryption Migration'],
  ['检测存储是否为旧格式（未加密），如果是则提示并执行迁移。', 'Detect if storage is legacy format (unencrypted), prompt and execute migration if so.'],
  ['此函数应在 CLI 入口处调用。迁移过程：', 'This function should be called at CLI entry. Migration process:'],
  ['1. 读取明文存储', '1. Read plaintext storage'],
  ['2. 确保用户设置了 master password', '2. Ensure user has set master password'],
  ['3. 加密所有 privateKey 字段', '3. Encrypt all privateKey fields'],
  ['4. 添加 encrypted 标记和密码校验值', '4. Add encrypted flag and password checksum'],
  ['5. 保存加密后的存储', '5. Save encrypted storage'],
  ['// 如果没有数据或已加密，跳过', '// Skip if no data or already encrypted'],
  ['// 检查是否有需要加密的私钥', '// Check if there are private keys to encrypt'],
  ["检测到钱包存储使用旧格式（明文私钥），需要迁移到加密格式。", "Detected wallet store using legacy format (plaintext private keys), migration to encrypted format required."],
  ['// 备份原始文件', '// Backup original file'],
  ['已备份原始文件至', 'Original file backed up to'],
  ['警告: 无法创建备份文件，继续迁移...', 'Warning: unable to create backup file, continuing migration...'],
  ['// 加密所有私钥', '// Encrypt all private keys'],
  ['钱包存储已成功迁移到加密格式。', 'Wallet store successfully migrated to encrypted format.'],
  ['验证当前 master password 是否与存储中的密码校验值匹配。', 'Verify if current master password matches the stored password checksum.'],
  ['如果存储未加密，返回 true。', 'Returns true if storage is unencrypted.'],
  ['// 没有校验值时跳过', '// Skip when no checksum'],
  ['确保密码已设置且正确。供 CLI 入口在执行需要私钥的命令前调用。', 'Ensure password is set and correct. Called by CLI entry before commands requiring private keys.'],
  ['// 未加密存储不需要密码', '// Unencrypted storage does not need password'],
  ['_masterPassword = null; // 清除错误密码', '_masterPassword = null; // Clear incorrect password'],
  ["throw new Error('密码错误：无法解密钱包存储。请检查密码是否正确。')", "throw new Error('Wrong password: unable to decrypt wallet store. Please check your password.')"],
  ['// 钱包组操作', '// Wallet Group Operations'],
  ['/** 获取所有钱包组 */', '/** Get all wallet groups */'],
  ['/** 获取单个钱包组 */', '/** Get a single wallet group */'],
  ['/** 保存钱包组（新增或更新） */', '/** Save wallet group (create or update) */'],
  ['/** 删除钱包组 */', '/** Delete wallet group */'],
  ['/** 向钱包组添加钱包（私钥将根据存储状态自动加密） */', '/** Add wallets to group (private keys auto-encrypted based on storage state) */'],
  ['// 去重检查', '// Deduplication check'],
  ['// 如果存储已加密，加密新钱包的私钥', '// If storage is encrypted, encrypt new wallet private keys'],
  ["throw new Error('存储已加密但未设置密码，请先调用 ensureMasterPassword()')", "throw new Error('Storage is encrypted but no password set, call ensureMasterPassword() first')"],
  ['/** 从钱包组移除钱包 */', '/** Remove wallet from group */'],
  ['// 钱包生成', '// Wallet Generation'],
  ['/** 生成新钱包（返回明文私钥，存储时由 addWalletsToGroup 负责加密） */', '/** Generate new wallets (returns plaintext private keys, encryption handled by addWalletsToGroup) */'],
  ['/** 从私钥恢复钱包信息 */', '/** Restore wallet info from private key */'],
  ['// 加密 / 导出（导出时解密，导入时加密）', '// Encryption / Export (decrypt on export, encrypt on import)'],
  ['/** 加密导出钱包存储（整体加密，用于备份） */', '/** Encrypted export of wallet store (whole-file encryption, for backup) */'],
  ['// 如果存储已加密，先解密私钥再整体加密', '// If storage is encrypted, decrypt private keys first then encrypt whole'],
  ['// 如果解密失败，保持原样', '// If decryption fails, keep as-is'],
  ['// 移除加密标记（导出的是明文数据的整体加密）', '// Remove encrypted flag (export is whole-file encryption of plaintext data)'],
  ['/** 解密导入钱包存储 */', '/** Decrypt and import wallet store */'],
  ['/** 导出钱包组为 CSV（自动解密私钥） */', '/** Export wallet group as CSV (auto-decrypts private keys) */'],
  ['// 如果存储已加密，解密私钥用于导出', '// If storage is encrypted, decrypt private keys for export'],
  ['// 解密失败时保持原样', '// Keep as-is on decryption failure'],
  ['/** 从 CSV 导入钱包 */', '/** Import wallets from CSV */'],
  ['// 跳过表头', '// Skip header'],
  ['// 验证私钥', '// Validate private key'],
  ['警告: 地址不匹配', 'Warning: address mismatch'],
  ['跳过无效私钥', 'Skipping invalid private key'],
  ['/** 导出所有钱包组为 JSON（兼容前端导入格式，自动解密私钥） */', '/** Export all wallet groups as JSON (compatible with frontend import format, auto-decrypts private keys) */'],
  ['// 如果存储已加密，解密私钥用于导出', '// If storage is encrypted, decrypt private keys for export'],
  ['/** 导出加密的钱包组 JSON */', '/** Export encrypted wallet groups JSON */'],
  ['/** 导入钱包组 JSON */', '/** Import wallet groups JSON */'],
  ['// 尝试解密', '// Try to decrypt'],
  ['// 备注管理', '// Note Management'],
  ['/** 获取钱包备注 */', '/** Get wallet note */'],
  ['/** 设置钱包备注 */', '/** Set wallet note */'],
  ['/** 获取所有备注 */', '/** Get all notes */'],

  // ===== data-source.ts =====
  ['ForgeX CLI DataSource -- 统一数据源门面', 'ForgeX CLI DataSource -- Unified Data Source Facade'],
  ['命令层唯一的数据访问接口。将所有数据适配器（CodexAdapter、RpcAdapter、', 'Single data access interface for the command layer. Wraps all data adapters (CodexAdapter, RpcAdapter,'],
  ['JitoAdapter、DataStore）统一封装，提供简洁的接口供命令层调用。', 'JitoAdapter, DataStore) into a unified facade with simple interfaces for command use.'],
  ['路由逻辑:', 'Routing logic:'],
  ['代币信息 / 价格 / K线 / 池信息  --> CodexAdapter (远程, 缓存穿透到 DataStore)', 'Token info / price / candlestick / pool info  --> CodexAdapter (remote, cache-through to DataStore)'],
  ['余额 / 账户信息 / 交易确认      --> RpcAdapter (链上)', 'Balance / account info / tx confirmation      --> RpcAdapter (on-chain)'],
  ['Bundle 发送 / 状态查询           --> JitoAdapter (Jito Block Engine)', 'Bundle send / status query           --> JitoAdapter (Jito Block Engine)'],
  ['交易记录 / 持仓 / 钱包组数据     --> DataStore (本地文件)', 'Trade records / positions / wallet group data     --> DataStore (local files)'],
  ['缓存穿透:', 'Cache-through:'],
  ['优先读 DataStore 本地缓存。如果 miss 或过期，则从远程 (Codex/RPC) 获取', 'Reads DataStore local cache first. On miss or expiry, fetches from remote (Codex/RPC),'],
  ['最新数据，写入 DataStore 后返回。', 'writes to DataStore, then returns.'],
  ['容错:', 'Fault tolerance:'],
  ['当 Codex API 不可用时，fallback 到 DataStore 中的历史缓存。', 'When Codex API is unavailable, falls back to historical cache in DataStore.'],
  ['RPC/Jito 不可用时，抛出 DataSourceError 供命令层处理。', 'When RPC/Jito unavailable, throws DataSourceError for command layer to handle.'],
  ['// 统一错误类型', '// Unified Error Type'],
  ['/** 错误来源 */', '/** Error source */'],
  ['/** 是否已 fallback 到缓存 */', '/** Whether fallback to cache was used */'],
  ['/** 原始错误 */', '/** Original error */'],
  ['// Cache过期阈值 (ms)', '// Cache expiry thresholds (ms)'],
  ['/** 代币信息缓存有效期: 10 分钟 */', '/** Token info cache TTL: 10 minutes */'],
  ['/** 池信息缓存有效期: 2 分钟 */', '/** Pool info cache TTL: 2 minutes */'],
  ['/** SOL 价格缓存有效期: 1 分钟 */', '/** SOL price cache TTL: 1 minute */'],
  ['// DataSource 实现', '// DataSource Implementation'],
  ['// 代币信息 -- CodexAdapter + DataStore 缓存穿透', '// Token Info -- CodexAdapter + DataStore cache-through'],
  ['获取代币基本信息。', 'Get basic token info.'],
  ['流程:', 'Flow:'],
  ['1. 先查 DataStore 缓存', '1. Check DataStore cache first'],
  ['2. 缓存命中且未过期 -> 直接返回', '2. Cache hit and not expired -> return directly'],
  ['3. 缓存 miss 或过期 -> 从 Codex 获取并写入 DataStore', '3. Cache miss or expired -> fetch from Codex and write to DataStore'],
  ['4. Codex 不可用 -> fallback 到 DataStore 陈旧缓存 (如有)', '4. Codex unavailable -> fallback to stale DataStore cache (if any)'],
  ['// 1. 查本地缓存', '// 1. Check local cache'],
  ['// 2. 从 Codex 获取', '// 2. Fetch from Codex'],
  ['// 写入 DataStore', '// Write to DataStore'],
  ['// 3. Codex 不可用, fallback 到陈旧缓存', '// 3. Codex unavailable, fallback to stale cache'],
  ['获取代币信息失败', 'Failed to get token info'],
  ['获取代币详细市场数据 (包含价格、交易量、持有者等)。', 'Get detailed token market data (including price, volume, holders, etc).'],
  ['直接从 Codex 获取, 不做本地缓存穿透 (市场数据实时性要求高)。', 'Fetches directly from Codex without local cache-through (market data requires high timeliness).'],
  ['获取代币市场数据失败', 'Failed to get token market data'],
  ['// 价格 -- CodexAdapter + DataStore 缓存穿透', '// Price -- CodexAdapter + DataStore cache-through'],
  ['获取代币价格 (SOL 和 USD)。', 'Get token price (SOL and USD).'],
  ['缓存穿透: 先查 DataStore pool-info 缓存的价格, 过期则从 Codex 获取。', 'Cache-through: checks DataStore pool-info cached price first, fetches from Codex if expired.'],
  ['// fallback: 从 DataStore 的 pool-info 中读取历史价格', '// fallback: read historical price from DataStore pool-info'],
  ['获取代币价格失败', 'Failed to get token price'],
  ['获取 SOL 价格 (USD)。', 'Get SOL price (USD).'],
  ['缓存穿透: 先查 DataStore, 过期则从 Codex 获取并更新。', 'Cache-through: checks DataStore first, fetches from Codex and updates if expired.'],
  ['// Check cache是否过期 -- getSolPrice 返回的是数字, 需要额外检查时间', '// Check if cache is expired -- getSolPrice returns a number, needs extra time check'],
  ['// DataStore 内部的 MemoryCache 有 30s TTL, 这里再加一层文件级 TTL', '// DataStore internal MemoryCache has 30s TTL, adding another file-level TTL here'],
  ['// 由于 DataStore.getSolPrice() 已经有 MemoryCache, 这里信任它即可', '// Since DataStore.getSolPrice() already has MemoryCache, trust it here'],
  ['// 但如果明确需要刷新, 下面的 try 会尝试', '// But if refresh is explicitly needed, the try below will attempt it'],
  ['// fallback: 使用缓存', '// fallback: use cache'],
  ['获取 SOL 价格失败', 'Failed to get SOL price'],
  ['// 池/流动性信息 -- CodexAdapter + DataStore 缓存穿透', '// Pool/Liquidity Info -- CodexAdapter + DataStore cache-through'],
  ['获取流动性池信息。', 'Get liquidity pool info.'],
  ['缓存穿透: DataStore 有效 -> 返回; miss/过期 -> Codex 获取并写入。', 'Cache-through: DataStore valid -> return; miss/expired -> fetch from Codex and write.'],
  ['// 2. 从 Codex 获取', '// 2. Fetch from Codex'],
  ['// fallback 到陈旧缓存', '// fallback to stale cache'],
  ['获取池信息失败', 'Failed to get pool info'],
  ['// Candlestick Data -- CodexAdapter (无本地缓存)', '// Candlestick Data -- CodexAdapter (no local cache)'],
  ['获取 K线 (OHLCV) 数据。', 'Get candlestick (OHLCV) data.'],
  ['K线数据量大且时效性强, 不做本地缓存。', 'Candlestick data is large and time-sensitive, no local caching.'],
  ['获取 K线数据失败', 'Failed to get candlestick data'],
  ['获取代币的交易对列表。', 'Get trading pair list for a token.'],
  ['获取交易对失败', 'Failed to get trading pairs'],
  ['// 余额查询 -- RpcAdapter (链上实时数据)', '// Balance Queries -- RpcAdapter (on-chain real-time data)'],
  ['获取单个钱包的 SOL 余额。', 'Get SOL balance for a single wallet.'],
  ['获取 SOL 余额失败', 'Failed to get SOL balance'],
  ['批量获取多个钱包的 SOL 余额。', 'Batch get SOL balances for multiple wallets.'],
  ['批量获取 SOL 余额失败', 'Failed to batch get SOL balances'],
  ['获取单个钱包的单个 Token 余额。', 'Get single token balance for a wallet.'],
  ['获取 Token 余额失败', 'Failed to get token balance'],
  ['批量获取多个钱包在指定代币上的余额。', 'Batch get token balances for multiple wallets on a specific token.'],
  ['批量获取 Token 余额失败', 'Failed to batch get token balances'],
  ['获取单个钱包的所有 Token 账户。', 'Get all token accounts for a single wallet.'],
  ['获取 Token 账户列表失败', 'Failed to get token account list'],
  ['获取钱包组在指定代币上的完整余额数据。', 'Get complete balance data for wallet group on a specific token.'],
  ['从 RPC 实时获取并更新 DataStore, 然后返回 BalancesFile。', 'Fetches from RPC in real-time, updates DataStore, then returns BalancesFile.'],
  ['// 并行获取 SOL 和 Token 余额', '// Fetch SOL and Token balances in parallel'],
  ['// 批量写入 DataStore', '// Batch write to DataStore'],
  ['// fallback: 返回 DataStore 中的历史数据', '// fallback: return historical data from DataStore'],
  ['获取钱包余额失败', 'Failed to get wallet balances'],
  ['// 交易状态 -- RpcAdapter', '// Transaction Status -- RpcAdapter'],
  ['查询单笔交易的确认状态。', 'Query confirmation status of a single transaction.'],
  ['获取交易状态失败', 'Failed to get transaction status'],
  ['获取交易详情。', 'Get transaction details.'],
  ['获取交易详情失败', 'Failed to get transaction details'],
  ['批量查询交易状态。', 'Batch query transaction statuses.'],
  ['批量获取交易状态失败', 'Failed to batch get transaction statuses'],
  ['// Bundle 操作 -- JitoAdapter', '// Bundle Operations -- JitoAdapter'],
  ['发送 Bundle 到 Jito Block Engine。', 'Send bundle to Jito Block Engine.'],
  ['发送 Bundle 失败', 'Failed to send bundle'],
  ['查询 Bundle 状态。', 'Query bundle status.'],
  ['获取 Bundle 状态失败', 'Failed to get bundle status'],
  ['等待 Bundle 确认。', 'Wait for bundle confirmation.'],
  ['等待 Bundle 确认失败', 'Failed waiting for bundle confirmation'],
  ['// 单笔交易发送 -- JitoAdapter (sendTransaction)', '// Single Transaction Sending -- JitoAdapter (sendTransaction)'],
  ['通过 Jito 发送单笔交易。', 'Send single transaction via Jito.'],
  ['发送交易失败', 'Failed to send transaction'],
  ['通过 RPC 确认交易状态。', 'Confirm transaction status via RPC.'],
  ['确认交易失败', 'Failed to confirm transaction'],
  ['// 交易记录 -- DataStore (本地文件)', '// Trade Records -- DataStore (local files)'],
  ['获取交易记录。', 'Get trade records.'],
  ['获取指定钱包的交易记录。', 'Get trade records for a specific wallet.'],
  ['追加交易记录。', 'Append trade records.'],
  ['写入交易记录失败', 'Failed to write trade records'],
  ['// 持仓数据 -- DataStore (本地文件)', '// Position Data -- DataStore (local files)'],
  ['获取持仓数据。', 'Get position data.'],
  ['更新持仓数据。', 'Update position data.'],
  ['更新持仓失败', 'Failed to update positions'],
  ['// 余额快照 -- DataStore (本地文件)', '// Balance Snapshots -- DataStore (local files)'],
  ['获取本地缓存的余额快照。', 'Get locally cached balance snapshot.'],
  ['更新余额快照。', 'Update balance snapshot.'],
  ['更新余额快照失败', 'Failed to update balance snapshot'],
  ['// 全局数据 -- DataStore', '// Global Data -- DataStore'],
  ['获取手续费配置。', 'Get fee configuration.'],
  ['保存手续费配置。', 'Save fee configuration.'],
  ['保存手续费配置失败', 'Failed to save fee configuration'],
  ['// DataStore 工具方法', '// DataStore Utility Methods'],
  ['列出所有有数据的代币 CA。', 'List all token CAs with data.'],
  ['列出某个代币下所有有数据的钱包组 ID。', 'List all wallet group IDs with data for a token.'],
  ['// 交易追踪 -- TxTracker', '// Transaction Tracking -- TxTracker'],
  ['追踪单笔交易。', 'Track a single transaction.'],
  ['轮询确认后自动写入 DataStore (交易记录 + 持仓 + 余额)。', 'Auto-writes to DataStore after polling confirmation (trade records + positions + balances).'],
  ['追踪 Jito Bundle。', 'Track a Jito Bundle.'],
  ['Bundle 确认后逐个处理内部交易并写入 DataStore。', 'Processes internal transactions individually after bundle confirmation and writes to DataStore.'],
  ['批量追踪多笔独立交易。', 'Batch track multiple independent transactions.'],
  ['检查所有数据源的健康状态。', 'Check health status of all data sources.'],

  // ===== Common patterns in commands =====
  ['交易手续费', 'trade fee'],
  ['小费地址', 'tip address'],
  ['推荐人手续费', 'referral fee'],
  ['批量分发手续费', 'batch transfer fee'],
  ['批量归集手续费', 'batch collection fee'],
  ['多转多手续费', 'multi-to-multi fee'],
  ['主动发射抢筹手续费', 'active launch sniper fee'],
  ['主动发射抢筹外盘抢筹手续费', 'active launch sniper external fee'],
  ['同区块换手手续费', 'same-block turnover fee'],
  ['同区块换手多跳手续费', 'same-block turnover multi-hop fee'],
  ['同区块刷量手续费', 'same-block volume fee'],

  // ===== commands/trade =====
  ['交易命令组 - 真实交易执行', 'Trade command group - real trade execution'],
  ['优化: 交易发出后不等确认、不追踪详情，直接返回 txHash', 'Optimization: returns txHash directly after sending, without waiting for confirmation or tracking details'],
  ["'交易操作'", "'Trade operations'"],
  ['// forgex trade buy - 真实批量买入', '// forgex trade buy - real batch buy'],
  ["'批量买入代币'", "'Batch buy tokens'"],
  ["'钱包组 ID'", "'Wallet group ID'"],
  ["'代币合约地址'", "'Token contract address'"],
  ["'每个钱包买入金额 (SOL)'", "'Amount per wallet (SOL)'"],
  ["'滑点 (bps, 例如 300 = 3%)'", "'Slippage (bps, e.g. 300 = 3%)'"],
  ["'优先费 (SOL)'", "'Priority fee (SOL)'"],
  ["'仅模拟，不实际执行'", "'Dry run only, no actual execution'"],
  ["'--group 必须是有效数字'", "'--group must be a valid number'"],
  ["'--amount 必须是大于 0 的数字'", "'--amount must be a number greater than 0'"],
  ["'--slippage 必须是 1-5000 之间的数字'", "'--slippage must be a number between 1-5000'"],
  ["'--priority-fee 必须是非负数字'", "'--priority-fee must be a non-negative number'"],
  ['`钱包组 ${groupId} 不存在`', '`Wallet group ${groupId} does not exist`'],
  ["'钱包组中没有钱包'", "'No wallets in wallet group'"],
  ['`获取代币 ${options.token} 的交易上下文...`', '`Fetching trade context for token ${options.token}...`'],
  ['`DEX: ${context.exchangeName}, 价格: ${context.priceInSol} SOL`', '`DEX: ${context.exchangeName}, Price: ${context.priceInSol} SOL`'],
  ['`提交买入交易: ${wallets.length} 个钱包, 每个 ${options.amount} SOL...`', '`Submitting buy trades: ${wallets.length} wallets, ${options.amount} SOL each...`'],
  ["'买入失败'", "'Buy failed'"],
  ['// forgex trade sell - 真实批量卖出', '// forgex trade sell - real batch sell'],
  ["'批量卖出代币'", "'Batch sell tokens'"],
  ["'卖出数量: 百分比(如50%) 或 all(全部) 或 具体代币数量'", "'Sell amount: percentage (e.g. 50%), all, or specific token amount'"],
  ['--slippage 必须是 1-5000 之间的数字', '--slippage must be a number between 1-5000'],
  ['--priority-fee 必须是非负数字', '--priority-fee must be a non-negative number'],
  ['// 预验证 amount 格式', '// Pre-validate amount format'],
  ['`无效的百分比: ${amountRaw}，有效范围 1%-100%`', '`Invalid percentage: ${amountRaw}, valid range 1%-100%`'],
  ['`无效的卖出数量: ${amountRaw}，请输入正数、百分比(如50%)或 all`', '`Invalid sell amount: ${amountRaw}, enter a positive number, percentage (e.g. 50%), or all`'],
  ['查询各钱包代币余额...', 'Querying token balances for wallets...'],
  ['所有钱包的代币余额为 0，无法卖出', 'All wallet token balances are 0, cannot sell'],
  ['`提交卖出交易: ${wallets.length} 个钱包...`', '`Submitting sell trades: ${wallets.length} wallets...`'],
  ["'卖出失败'", "'Sell failed'"],
  ['// forgex trade batch - 真实批量交易（刷量模式）', '// forgex trade batch - real batch trade (volume mode)'],
  ["'批量交易（刷量模式）'", "'Batch trade (volume mode)'"],
  ["'交易类型: buy | sell | buyWithSell'", "'Trade type: buy | sell | buyWithSell'"],
  ["'刷量模式: 1b1s | 1b2s | 1b3s | 2b1s | 3b1s'", "'Volume mode: 1b1s | 1b2s | 1b3s | 2b1s | 3b1s'"],
  ["'交易金额 (SOL)'", "'Trade amount (SOL)'"],
  ["'滑点 (bps)', '300'", "'Slippage (bps)', '300'"],
  ['`--type 无效: "${options.type}"，必须是 buy | sell | buyWithSell`', '`--type invalid: "${options.type}", must be buy | sell | buyWithSell`'],
  ['`--mode 无效: "${options.mode}"，必须是 1b1s | 1b2s | 1b3s | 2b1s | 3b1s`', '`--mode invalid: "${options.mode}", must be 1b1s | 1b2s | 1b3s | 2b1s | 3b1s`'],
  ['`提交批量交易: 模式 ${options.mode}, 类型 ${options.type}, ${wallets.length} 钱包...`', '`Submitting batch trade: mode ${options.mode}, type ${options.type}, ${wallets.length} wallets...`'],
  ["'批量交易失败'", "'Batch trade failed'"],
  ['// forgex trade sniper - 真实狙击买入', '// forgex trade sniper - real sniper buy'],
  ["'狙击买入'", "'Sniper buy'"],
  ["'每个钱包买入金额（逗号分隔，单位SOL）'", "'Buy amount per wallet (comma-separated, in SOL)'"],
  ["'滑点 (bps, 例如 500 = 5%)'", "'Slippage (bps, e.g. 500 = 5%)'"],
  ['`--amounts 中第 ${i + 1} 个金额无效`', '`Amount #${i + 1} in --amounts is invalid`'],
  ['`金额数量 (${amounts.length}) 与钱包数量 (${group.wallets.length}) 不匹配`', '`Amount count (${amounts.length}) does not match wallet count (${group.wallets.length})`'],
  ['`提交狙击交易: ${wallets.length} 个钱包...`', '`Submitting sniper trades: ${wallets.length} wallets...`'],
  ["'狙击交易失败'", "'Sniper trade failed'"],

  // ===== commands/query =====
  ['查询命令组', 'Query command group'],
  ['数据源: DataSource 统一门面 (3.0g 迁移)', 'Data source: DataSource unified facade (3.0g migration)'],
  ['// 输入验证辅助函数', '// Input validation helper functions'],
  ['/** 验证 Solana 公钥地址格式 */', '/** Validate Solana public key address format */'],
  ['`无效的${label}格式: ${address}`', '`Invalid ${label} format: ${address}`'],
  ['/** 验证正整数 */', '/** Validate positive integer */'],
  ['`${label} 必须是正整数，收到: ${value}`', '`${label} must be a positive integer, received: ${value}`'],
  ["'查询操作'", "'Query operations'"],
  ["'查询钱包余额'", "'Query wallet balance'"],
  ["'钱包地址'", "'Wallet address'"],
  ["'代币合约地址（不填则查 SOL）'", "'Token contract address (queries SOL if omitted)'"],
  ["'代币合约地址'", "'Token contract address'"],
  ['// 查询 SOL 余额 -- 通过 DataSource -> RpcAdapter', '// Query SOL balance -- via DataSource -> RpcAdapter'],
  ['// 查询代币余额 -- 通过 DataSource -> RpcAdapter', '// Query token balance -- via DataSource -> RpcAdapter'],
  ['// 尝试获取代币符号信息', '// Try to get token symbol info'],
  ['// 代币信息获取失败不影响余额显示', '// Token info fetch failure does not affect balance display'],
  ["'未持有该代币'", "'Token not held'"],
  ["'查询余额失败'", "'Balance query failed'"],
  ["'查询代币价格'", "'Query token price'"],
  ['// 并行获取代币信息和价格 -- 通过 DataSource -> CodexAdapter', '// Fetch token info and price in parallel -- via DataSource -> CodexAdapter'],
  ['// 格式化交易对信息', '// Format trading pair info'],
  ["'查询价格失败'", "'Price query failed'"],
  ["'查询 K 线数据'", "'Query candlestick data'"],
  ["'周期: 1m | 5m | 15m | 1h | 4h | 1d'", "'Interval: 1m | 5m | 15m | 1h | 4h | 1d'"],
  ["'数据条数'", "'Data count'"],
  ['`--interval 必须是以下之一: ${validIntervals.join(\', \')}\uff0c收到: ${options.interval}`', '`--interval must be one of: ${validIntervals.join(\', \')}, received: ${options.interval}`'],
  ['`--count 必须是正整数，收到: ${options.count}`', '`--count must be a positive integer, received: ${options.count}`'],
  ['// Codex API 使用不同的 resolution 格式', '// Codex API uses different resolution format'],
  ['// 先获取代币的 pairAddress 用于 K线查询', '// Get token pairAddress first for candlestick query'],
  ['// 如果获取不到 pairAddress，使用 token 地址', '// If pairAddress unavailable, use token address'],
  ['// 通过 DataSource -> CodexAdapter 获取 K线数据', '// Get candlestick data via DataSource -> CodexAdapter'],
  ["'查询 K 线数据失败'", "'Candlestick data query failed'"],
  ["'查询交易记录'", "'Query trade records'"],
  ["'按代币过滤'", "'Filter by token'"],
  ["'页码'", "'Page number'"],
  ["'每页数量'", "'Page size'"],
  ['// 按代币过滤: 从 DataStore 读取本地交易记录', '// Filter by token: read local trade records from DataStore'],
  ['// 手动分页', '// Manual pagination'],
  ["'暂无交易记录'", "'No trade records'"],
  ["'交易哈希'", "'Tx Hash'"],
  ["'类型'", "'Type'"],
  ["'钱包'", "'Wallet'"],
  ["'SOL 数量'", "'SOL Amount'"],
  ["'Token 数量'", "'Token Amount'"],
  ["'时间'", "'Time'"],
  ['// 无代币过滤: 汇总所有代币的交易记录', '// No token filter: aggregate all token trade records'],
  ['// 按时间倒序排列', '// Sort by time descending'],
  ["'查询交易记录失败'", "'Trade records query failed'"],
  ["'查询监控数据'", "'Query monitoring data'"],
  ['// 指定代币: 从 DataStore 读取持仓 + 获取实时价格', '// Specific token: read positions from DataStore + get real-time price'],
  ['// 计算未实现盈亏', '// Calculate unrealized P&L'],
  ['// 无指定代币: 汇总所有代币的持仓数据', '// No specific token: aggregate all token positions'],
  ['// 价格获取失败，使用默认值', '// Price fetch failed, use default'],
  ["'暂无持仓数据'", "'No position data'"],
  ["'查询监控数据失败'", "'Monitoring data query failed'"],

  // ===== commands/wallet (common) =====
  ['`（类型: ${options.type}）`', '`(type: ${options.type})`'],
  ['`没有找到钱包组${filterMsg}`', '`No wallet groups found${filterMsg}`'],
  ["'名称'", "'Name'"],
  ["'类型'", "'Type'"],
  ["'钱包数'", "'Wallet Count'"],
  ["'监控类型'", "'Monitor Type'"],
  ["'备注'", "'Note'"],
  ["'获取钱包组列表失败'", "'Failed to list wallet groups'"],
  ["'查看钱包组详情'", "'View wallet group details'"],
  ["'钱包组 ID'", "'Wallet group ID'"],
  ["'显示私钥（危险操作）'", "'Show private keys (dangerous)'"],
  ['`无效的钱包组 ID "${options.id}"，请提供数字 ID`', '`Invalid wallet group ID "${options.id}", please provide a numeric ID`'],
  ['// 如果需要显示私钥，先确保密码已设置且正确', '// If showing private keys, ensure password is set and correct first'],
  ['警告：即将显示私钥明文，请确保当前环境安全，切勿在公共场所或共享屏幕时使用此命令', 'Warning: About to display plaintext private keys. Ensure a secure environment. Never use this command in public or screen-sharing sessions'],
  ['`钱包组 ${groupId} 不存在`', '`Wallet group ${groupId} does not exist`'],
  ["'获取钱包组详情失败'", "'Failed to get wallet group details'"],
  ["'删除钱包组'", "'Delete wallet group'"],
  ["'跳过确认'", "'Skip confirmation'"],
  ['`无效的钱包组 ID "${options.id}"，请提供数字 ID`', '`Invalid wallet group ID "${options.id}", provide a numeric ID`'],
  ['// 检查本地是否存在该钱包组', '// Check if wallet group exists locally'],
  ['// 非 --force 模式下，提示用户确认', '// In non --force mode, prompt user for confirmation'],
  ['`确认删除钱包组 "${group.name}" (ID: ${groupId}, ${group.wallets.length} 个钱包)？此操作不可恢复。`', '`Confirm delete wallet group "${group.name}" (ID: ${groupId}, ${group.wallets.length} wallets)? This action is irreversible.`'],
  ["'已取消删除操作'", "'Delete operation cancelled'"],
  ['// 纯本地删除', '// Pure local deletion'],
  ["'钱包组已删除'", "'Wallet group deleted'"],
  ["'删除钱包组失败'", "'Failed to delete wallet group'"],
  ["'生成新钱包'", "'Generate new wallets'"],
  ["'目标钱包组 ID'", "'Target wallet group ID'"],
  ["'生成数量'", "'Count to generate'"],
  ['`无效的钱包组 ID "${options.group}"，请提供数字 ID`', '`Invalid wallet group ID "${options.group}", provide a numeric ID`'],
  ['`无效的生成数量 "${options.count}"，请提供正整数`', '`Invalid count "${options.count}", provide a positive integer`'],
  ['`钱包组 ${groupId} 不存在`', '`Wallet group ${groupId} does not exist`'],
  ['`钱包数量超限：当前 ${group.wallets.length} 个，最多再生成 ${100 - group.wallets.length} 个（上限 100）`', '`Wallet count exceeded: currently ${group.wallets.length}, max ${100 - group.wallets.length} more (limit 100)`'],
  ['// 保存明文私钥用于输出（addWalletsToGroup 可能会加密 wallets 中的 privateKey）', '// Save plaintext private keys for output (addWalletsToGroup may encrypt privateKey in wallets)'],
  ['// 纯本地存储（如果存储已加密，此函数会加密 wallets 的 privateKey 字段）', '// Pure local storage (if store is encrypted, this function encrypts privateKey fields)'],
  ['`已生成 ${plaintextKeys.length} 个钱包到组 ${groupId}`', '`Generated ${plaintextKeys.length} wallets to group ${groupId}`'],
  ["'地址'", "'Address'"],
  ["'私钥'", "'Private Key'"],
  ["'生成钱包失败'", "'Failed to generate wallets'"],
  ["'添加钱包到钱包组'", "'Add wallet to group'"],
  ["'私钥（Base58 编码）'", "'Private key (Base58 encoded)'"],
  // Wallet group validation
  ['// 验证钱包组存在', '// Verify wallet group exists'],
  ['// 验证私钥有效性', '// Validate private key'],
  ["'无效的私钥：请提供有效的 Base58 编码私钥'", "'Invalid private key: provide a valid Base58 encoded private key'"],
  ['// 检查地址是否已存在于该组', '// Check if address already exists in group'],
  ['`钱包 ${wallet.walletAddress} 已存在于钱包组 ${groupId} 中，跳过重复添加`', '`Wallet ${wallet.walletAddress} already exists in group ${groupId}, skipping duplicate`'],
  ['// 纯本地存储', '// Pure local storage'],
  ["'添加钱包失败'", "'Failed to add wallet'"],
  ["'从钱包组移除钱包'", "'Remove wallet from group'"],
  ['// 验证地址是否存在于该钱包组中', '// Verify address exists in wallet group'],
  ['`钱包 ${options.address} 不在钱包组 ${groupId} 中`', '`Wallet ${options.address} is not in wallet group ${groupId}`'],
  ['// 纯本地移除', '// Pure local removal'],
  ["'移除钱包失败'", "'Failed to remove wallet'"],
  ["'从 CSV 文件导入钱包'", "'Import wallets from CSV file'"],
  ["'CSV 文件路径'", "'CSV file path'"],
  ['`无效的钱包组 ID "${options.group}"，请提供正整数`', '`Invalid wallet group ID "${options.group}", provide a positive integer`'],
  ['// 验证钱包组存在', '// Verify wallet group exists'],
  ['// 验证文件存在', '// Verify file exists'],
  ['`CSV 文件不存在: ${options.file}`', '`CSV file does not exist: ${options.file}`'],
  ["'CSV 文件中没有有效的钱包数据'", "'No valid wallet data in CSV file'"],
  ['// 纯本地存储', '// Pure local storage'],
  ["'导入钱包失败'", "'Failed to import wallets'"],
  ["'导出钱包组为 CSV 文件'", "'Export wallet group as CSV file'"],
  ["'输出文件路径'", "'Output file path'"],
  ['`无效的钱包组 ID "${options.group}"，请提供正整数`', '`Invalid wallet group ID "${options.group}", provide a positive integer`'],
  ["'导出钱包失败'", "'Failed to export wallets'"],
  ["'从 JSON 文件导入钱包组'", "'Import wallet groups from JSON file'"],
  ["'JSON 文件路径'", "'JSON file path'"],
  ["'解密密码（加密文件需要）'", "'Decryption password (required for encrypted files)'"],
  ['// 验证文件存在', '// Verify file exists'],
  ['`JSON 文件不存在: ${options.file}`', '`JSON file does not exist: ${options.file}`'],
  ["'JSON 文件中没有有效的钱包组数据（如果是加密文件，请检查 --password 是否正确）'", "'No valid wallet group data in JSON file (if encrypted, check --password)'"],
  ['// 纯本地存储（通过 saveGroup + addWalletsToGroup 确保私钥正确加密）', '// Pure local storage (saveGroup + addWalletsToGroup ensure correct encryption)'],
  ['// 先保存空钱包组', '// Save empty wallet group first'],
  ['// 通过 addWalletsToGroup 添加钱包，该函数会自动处理加密', '// Add wallets via addWalletsToGroup, which handles encryption automatically'],
  ["'导入钱包组失败'", "'Failed to import wallet groups'"],
  ["'导出所有钱包组为 JSON 文件'", "'Export all wallet groups as JSON file'"],
  ["'加密导出'", "'Encrypted export'"],
  ["'加密密码'", "'Encryption password'"],
  ["'没有钱包组可导出'", "'No wallet groups to export'"],
  ["'加密导出需要密码，使用 --password 或设置 FORGEX_PASSWORD 环境变量'", "'Encrypted export requires password, use --password or set FORGEX_PASSWORD env var'"],
  ["'导出钱包组失败'", "'Failed to export wallet groups'"],
  ["'查看钱包组概览'", "'View wallet group overview'"],
  ["'钱包组 ID（逗号分隔）'", "'Wallet group IDs (comma-separated)'"],
  ['// 验证所有 groupId 都是有效正整数', '// Validate all groupIds are valid positive integers'],
  ['`无效的钱包组 ID 列表 "${options.groups}"，请提供逗号分隔的正整数`', '`Invalid wallet group ID list "${options.groups}", provide comma-separated positive integers`'],
  ['// 验证本地是否存在这些钱包组', '// Verify wallet groups exist locally'],
  ['`以下钱包组在本地不存在: ${missingIds.join(\', \')}`', '`The following wallet groups do not exist locally: ${missingIds.join(\', \')}`'],
  ['// 从 DataStore 本地数据构建概览', '// Build overview from DataStore local data'],
  ['// 确定要查询的代币列表', '// Determine token list to query'],
  ['// 尝试获取代币价格', '// Try to get token price'],
  ['// 价格不可用，跳过价值计算', '// Price unavailable, skip value calculation'],
  ["'暂无钱包组概览数据'", "'No wallet group overview data'"],
  ["'总价值(SOL)'", "'Total Value(SOL)'"],
  ["'总盈亏(SOL)'", "'Total P&L(SOL)'"],
  ["'已实现'", "'Realized'"],
  ["'未实现'", "'Unrealized'"],
  ["'均价'", "'Avg Cost'"],
  ["'获取钱包组概览失败'", "'Failed to get wallet group overview'"],
  ["'生成靓号地址（自定义后缀/前缀）'", "'Generate vanity address (custom suffix/prefix)'"],
  ["'地址后缀（如 pump）'", "'Address suffix (e.g. pump)'"],
  ["'地址前缀'", "'Address prefix'"],
  ["'grind 线程数'", "'Grind thread count'"],
  ['未检测到 solana-keygen，请先安装 Solana CLI 工具链', 'solana-keygen not found, please install Solana CLI toolchain first'],
  ['安装方式: sh -c "$(curl -sSfL https://release.anza.xyz/stable/install)" 或访问 https://docs.solanalabs.com/cli/install', 'Install: sh -c "$(curl -sSfL https://release.anza.xyz/stable/install)" or visit https://docs.solanalabs.com/cli/install'],
  ['`无效的生成数量 "${options.count}"，请提供正整数`', '`Invalid count "${options.count}", provide a positive integer`'],
  ["'--suffix 不能为空'", "'--suffix cannot be empty'"],
  ['// 验证后缀只包含 Base58 字符', '// Verify suffix contains only Base58 characters'],
  ['`无效的后缀 "${suffix}"，只支持 Base58 字符（不含 0, O, I, l）`', '`Invalid suffix "${suffix}", only Base58 characters supported (no 0, O, I, l)`'],
  ['`无效的前缀 "${options.prefix}"，只支持 Base58 字符（不含 0, O, I, l）`', '`Invalid prefix "${options.prefix}", only Base58 characters supported (no 0, O, I, l)`'],
  ['// 构建 solana-keygen grind 参数', '// Build solana-keygen grind arguments'],
  ['`无效的线程数 "${options.threads}"，请提供正整数`', '`Invalid thread count "${options.threads}", provide a positive integer`'],
  ['`正在生成 ${count} 个以 "${suffix}" 结尾的靓号地址，请耐心等待...`', '`Generating ${count} vanity addresses ending with "${suffix}", please wait...`'],
  ["'后缀较长，生成时间可能需要数分钟甚至更久'", "'Long suffix, generation may take minutes or longer'"],
  ['// 在 VANITY_DIR 下执行 grind，生成的 .json 文件会落在该目录', '// Execute grind in VANITY_DIR, generated .json files will be in that directory'],
  ["'solana-keygen grind 执行失败'", "'solana-keygen grind execution failed'"],
  ['// 解析生成结果，solana-keygen 输出格式: "Wrote keypair to <address>.json"', '// Parse generation results, solana-keygen output format: "Wrote keypair to <address>.json"'],
  ['// --starts-and-ends-with 模式下需要手动控制 count', '// In --starts-and-ends-with mode, need to manually control count'],
  ["'未能解析到生成的密钥文件'", "'Unable to parse generated key files'"],
  ['`成功生成 ${generatedFiles.length} 个靓号地址，已保存到 ${VANITY_DIR}`', '`Successfully generated ${generatedFiles.length} vanity addresses, saved to ${VANITY_DIR}`'],
  ["'文件路径'", "'File Path'"],
  ["'生成靓号地址失败'", "'Failed to generate vanity addresses'"],
  ["'列出已生成的靓号地址'", "'List generated vanity addresses'"],
  ["'按后缀过滤'", "'Filter by suffix'"],
  ["'暂无靓号地址，请先运行 forgex wallet grind 生成'", "'No vanity addresses yet, run forgex wallet grind first'"],
  ['`（后缀: ${options.suffix}）`', '`(suffix: ${options.suffix})`'],
  ['`没有找到匹配的靓号地址${filterMsg}`', '`No matching vanity addresses found${filterMsg}`'],
  ["'创建时间'", "'Created At'"],
  ["'获取靓号地址列表失败'", "'Failed to list vanity addresses'"],

  // ===== commands/tools =====
  ['`刷量已停止，共执行 ${currentRound} 轮`', '`Volume trading stopped, executed ${currentRound} rounds`'],
  ["'刷量失败'", "'Volume trading failed'"],
  ['// forgex tools robot-price - 真实价格机器人', '// forgex tools robot-price - real price robot'],
  ["'价格机器人（自动拉升/砸盘到目标价格）'", "'Price robot (auto pump/dump to target price)'"],
  ["'方向: up(拉升) | down(砸盘)'", "'Direction: up (pump) | down (dump)'"],
  ["'目标价格 (SOL)'", "'Target price (SOL)'"],
  ["'单次交易金额 (SOL)'", "'Amount per trade (SOL)'"],
  ["'金额类型: fixed | random'", "'Amount type: fixed | random'"],
  ["'最大金额（random 模式）'", "'Max amount (random mode)'"],
  ["'交易间隔 (毫秒)'", "'Trade interval (ms)'"],
  ["'总消耗上限 (SOL)'", "'Max total cost (SOL)'"],
  ["'滑点 (bps)'", "'Slippage (bps)'"],
  ["'后台长驻模式（默认开启，价格机器人本身即为持续执行）'", "'Daemon mode (enabled by default, price robot runs continuously)'"],
  ['// 密码验证', '// Password verification'],
  ['// 参数验证', '// Parameter validation'],
  ["'--group 必须是有效数字'", "'--group must be a valid number'"],
  ["'--amount 必须是大于 0 的数字'", "'--amount must be a number greater than 0'"],
  ["'--slippage 必须是 1-5000 之间的数字 (bps, 5000 = 50%)'", "'--slippage must be 1-5000 (bps, 5000 = 50%)'"],
  ["'--priority-fee 必须是非负数字'", "'--priority-fee must be a non-negative number'"],
  ["'--target-price 必须是大于 0 的数字'", "'--target-price must be a number greater than 0'"],
  ['// --direction 校验', '// --direction validation'],
  ['`--direction 无效: "${options.direction}"，必须是 up | down`', '`--direction invalid: "${options.direction}", must be up | down`'],
  ['`钱包组 ${groupId} 不存在`', '`Wallet group ${groupId} does not exist`'],
  ["'钱包组中没有钱包'", "'No wallets in wallet group'"],
  ['// 滑点转换: bps -> 百分比', '// Slippage conversion: bps -> percentage'],
  ['`获取代币 ${options.token} 的交易上下文...`', '`Fetching trade context for token ${options.token}...`'],
  ['`DEX: ${context.exchangeName}, 当前价格: ${context.priceInSol} SOL, 目标: ${targetPrice} SOL`', '`DEX: ${context.exchangeName}, Current price: ${context.priceInSol} SOL, Target: ${targetPrice} SOL`'],
  ["'模拟成功'", "'Simulation successful'"],
  ["'--max-cost 必须是大于 0 的数字'", "'--max-cost must be a number greater than 0'"],
  ['`价格机器人启动: ${options.direction === \'up\' ? \'拉升\' : \'砸盘\'} -> ${targetPrice} SOL`', '`Price robot started: ${options.direction === \'up\' ? \'pump\' : \'dump\'} -> ${targetPrice} SOL`'],
  ['// 刷新价格', '// Refresh price'],
  ['// 检查是否达到目标', '// Check if target reached'],
  ["'已达到目标价格'", "'Target price reached'"],
  ['// 检查成本上限', '// Check cost limit'],
  ['`已达到成本上限 ${maxCost} SOL`', '`Cost limit ${maxCost} SOL reached`'],
  ['// 计算交易金额', '// Calculate trade amount'],
  ['// sell 方向: amount 是 SOL 值，需要转换为等价代币数量', '// sell direction: amount is SOL value, convert to equivalent token amount'],
  ['// buy 方向: 直接传 SOL 金额', '// buy direction: pass SOL amount directly'],
  ['// SOL -> 代币数量: amount(SOL) / pricePerToken(SOL)', '// SOL -> token amount: amount(SOL) / pricePerToken(SOL)'],
  ['`第 ${executeCount} 次 ${tradeType}, 金额: ${amount.toFixed(6)} SOL ≈ ${tokenAmount.toFixed(2)} 代币, 当前价: ${currentPrice}`', '`Trade #${executeCount} ${tradeType}, amount: ${amount.toFixed(6)} SOL ≈ ${tokenAmount.toFixed(2)} tokens, current price: ${currentPrice}`'],
  ['`第 ${executeCount} 次 ${tradeType}, 金额: ${amount.toFixed(6)} SOL, 当前价: ${currentPrice}`', '`Trade #${executeCount} ${tradeType}, amount: ${amount.toFixed(6)} SOL, current price: ${currentPrice}`'],
  ['// JSON 模式下抑制 SDK 的 console.log', '// Suppress SDK console.log in JSON mode'],
  ['`执行出错: ${e.message}`', '`Execution error: ${e.message}`'],
  ['// 持续执行 (daemon 模式)', '// Continuous execution (daemon mode)'],
  ['`价格机器人已停止，共执行 ${executeCount} 次，总消耗 ${totalCost.toFixed(6)} SOL`', '`Price robot stopped, executed ${executeCount} times, total cost ${totalCost.toFixed(6)} SOL`'],
  ["'价格机器人启动失败'", "'Price robot start failed'"],

  // ===== P1/P2 validation comments =====
  ['// P2 fix: 验证 --token 是有效 Solana 公钥', '// P2 fix: validate --token is a valid Solana public key'],
  ['// P1 fix #1: 验证 --interval 必须是有效值', '// P1 fix #1: validate --interval is a valid value'],
  ['// P1 fix #2: 验证 --count 是正整数，非 NaN', '// P1 fix #2: validate --count is a positive integer, not NaN'],
  ['// P1 fix #3: 验证 --group, --page, --page-size 是有效正整数', '// P1 fix #3: validate --group, --page, --page-size are valid positive integers'],
  ['// P1 fix #4: 验证 --group 是有效正整数', '// P1 fix #4: validate --group is a valid positive integer'],
  ['// P2 fix: 验证 --token 地址（当提供时）', '// P2 fix: validate --token address (when provided)'],
  ['// P1 fix #5: 验证 --address 是有效 Solana 公钥', '// P1 fix #5: validate --address is a valid Solana public key'],
  ['// P1 fix #6: 验证 --token 地址（当提供时）', '// P1 fix #6: validate --token address (when provided)'],
  ['// 检查 solana-keygen 是否可用', '// Check if solana-keygen is available'],
]);

function processFile(filePath) {
  if (!fs.existsSync(filePath)) return;
  let content = fs.readFileSync(filePath, 'utf-8');
  let changed = false;

  for (const [from, to] of translations) {
    if (content.includes(from)) {
      content = content.replaceAll(from, to);
      changed = true;
    }
  }

  if (changed) {
    fs.writeFileSync(filePath, content, 'utf-8');
    console.log(`✓ ${path.relative('/Users/liu/sonic/forgex-cli', filePath)}`);
  }

  // Check remaining Chinese
  const chinesePattern = /[\u4e00-\u9fff\u3400-\u4dbf]+/g;
  const matches = [...content.matchAll(chinesePattern)];
  if (matches.length > 0) {
    const lines = content.split('\n');
    let count = 0;
    for (let i = 0; i < lines.length; i++) {
      if (chinesePattern.test(lines[i])) {
        chinesePattern.lastIndex = 0;
        count++;
        if (count <= 3) console.log(`  ⚠ L${i+1}: ${lines[i].trim().substring(0, 100)}`);
      }
    }
    if (count > 3) console.log(`  ... and ${count - 3} more lines`);
  }
}

const srcDir = '/Users/liu/sonic/forgex-cli/src';
function walkDir(dir) {
  const entries = fs.readdirSync(dir, { withFileTypes: true });
  for (const entry of entries) {
    const fullPath = path.join(dir, entry.name);
    if (entry.isDirectory()) walkDir(fullPath);
    else if (entry.name.endsWith('.ts')) processFile(fullPath);
  }
}
walkDir(srcDir);
